// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore1.Data;

#nullable disable

namespace TechStore1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore1.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Computadoras portátiles",
                            Icono = "bi bi-laptop",
                            Nombre = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Teléfonos inteligentes",
                            Icono = "bi bi-phone",
                            Nombre = "Smartphones"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Periféricos y más",
                            Icono = "bi bi-headset",
                            Nombre = "Accesorios"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Pantallas de alta resolución",
                            Icono = "bi bi-display",
                            Nombre = "Monitores"
                        });
                });

            modelBuilder.Entity("TechStore1.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Core i7, 16GB RAM, 512GB SSD",
                            Estado = true,
                            Imagen = "novabook-pro-14.jpg",
                            Nombre = "Laptop Pro X",
                            Precio = 1200.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Pantalla OLED, 128GB, 5G",
                            Estado = true,
                            Imagen = "pixelwave-x1.jpg",
                            Nombre = "Smartphone G",
                            Precio = 800.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descripcion = "Cancelación de ruido act.",
                            Estado = true,
                            Imagen = "sonicpulse-anc.jpg",
                            Nombre = "Auriculares Inalámbricos",
                            Precio = 150.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descripcion = "Monitor IPS para diseño",
                            Estado = true,
                            Imagen = "visiondock-27.jpg",
                            Nombre = "Monitor 4K 27",
                            Precio = 350.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "LIGHTSYNC RGB personalizable",
                            Estado = true,
                            Imagen = "gamecore-m5.jpg",
                            Nombre = "Mouse gamer RGB",
                            Precio = 80.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descripcion = "Switches RGB y blue",
                            Estado = true,
                            Imagen = "hyperstrike-k7.jpg",
                            Nombre = "Teclado Mecánico",
                            Precio = 90.00m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("TechStore1.Models.Producto", b =>
                {
                    b.HasOne("TechStore1.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TechStore1.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
